### PR TITLE
Merge latest upstream html-query-plan changes

### PR DESCRIPTION
**Pull request by kburtram**
Fixes https://github.com/Microsoft/azuredatastudio/issues/3491 and picks up upstream changes since April.

screen shot 2019-01-28 at 7 25 15 pm

### CODE REVIEW

**Comment by kburtram** [comment]
@anthonydresser could you please take a look at this when you have a chance?

**Review by anthonydresser — APPROVED** [review]

**Comment by kburtram** [comment]
@anthonydresser are you planning to merge into the release branch, create a new release, and update ADS references?  Or should I send a PR for that?  Alternatively, if you add permissions for me to managing this repo I can do this.

**Comment by anthonydresser** [comment]
I created a release 2.6 https://github.com/anthonydresser/html-query-plan/releases/tag/2.6

**Comment by kburtram** [comment]
@anthonydresser thanks!  I should have checked before asking I guessing 😄.

**Pull request merged**
